version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: football-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: football_db
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - football-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Football API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football-api
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: football_db
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Jakarta
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      JWT_EXPIRATION_HOURS: 24
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - football-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  football-network:
    driver: bridge
